### ISSUE TITLE
error in train.py

### ISSUE THREAD

**Issue by rfwaefd** [clovaai/donut#102]
Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '['.

I just input "python train.py --config config/train_cord.yaml --pretrained_model_name_or_path "naver-clova-ix/donut-base" --dataset_name_or_paths '["naver-clova-ix/cord-v2"]' --exp_version "test_experiment" " by typing in PowerShell.

Why is this? Is there a kind person who can help me?

**Comment by rfwaefd** [comment]
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    train(config)
  File "train.py", line 87, in train
    sort_json_key=config.sort_json_key,
  File "E:\xxx\xxx\xxx\xxx\donut-master\donut\util.py", line 64, in __init__
    self.dataset = load_dataset(dataset_name_or_path, split=self.split)
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\datasets\load.py", line 1729, in load_dataset
    **config_kwargs,
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\datasets\load.py", line 1494, in load_dataset_builder    data_files=data_files,
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\datasets\load.py", line 1216, in dataset_module_factory
    raise e1 from None
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\datasets\load.py", line 1185, in dataset_module_factory
    raise e
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\datasets\load.py", line 1162, in dataset_module_factory
    timeout=100.0,
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\datasets\utils\_hf_hub_fixes.py", line 152, in dataset_info
    return hf_api.dataset_info(repo_id, revision=revision, timeout=timeout, use_auth_token=use_auth_token)
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "C:\Users\123\AppData\Roaming\Python\Python37\site-packages\huggingface_hub\utils\_validators.py", line 173, in validate_repo_id
    "Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are"
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '['.

**Comment by xueyuG** [comment]
I also encountered this problem. Have you solved it?
