### ISSUE TITLE
What are acceptable input_size values?

### ISSUE THREAD

**Issue by htcml** [clovaai/donut#107]
I tried input_size = [480, 480] and train.py gives me the following error:

-------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 57, in train
    model_module = DonutModelPLModule(config)
  File "/home/thuan/donut/donut/lightning_module.py", line 35, in __init__
    ignore_mismatched_sizes=True,
  File "/home/thuan/donut/donut/donut/model.py", line 595, in from_pretrained
    model = super(DonutModel, cls).from_pretrained(pretrained_model_name_or_path, revision="official", *model_args, **kwargs)
  File "/axp/aida/data/platformds/aiservices/conda/envs/donut/lib/python3.7/site-packages/transformers/modeling_utils.py", line 2230, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/thuan/donut/donut/donut/model.py", line 387, in __init__
    name_or_path=self.config.name_or_path,
  File "/home/thuan/donut/donut/donut/model.py", line 70, in __init__
    num_classes=0,
  File "/axp/aida/data/platformds/aiservices/conda/envs/donut/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 500, in __init__
    downsample=PatchMerging if (i < self.num_layers - 1) else None
  File "/axp/aida/data/platformds/aiservices/conda/envs/donut/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 408, in __init__
    for i in range(depth)])
  File "/axp/aida/data/platformds/aiservices/conda/envs/donut/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 408, in <listcomp>
    for i in range(depth)])
  File "/axp/aida/data/platformds/aiservices/conda/envs/donut/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 281, in __init__
    mask_windows = window_partition(img_mask, self.window_size)  # num_win, window_size, window_size, 1
  File "/axp/aida/data/platformds/aiservices/conda/envs/donut/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 111, in window_partition
    x = x.view(B, H // window_size, window_size, W // window_size, window_size, C)
RuntimeError: shape '[1, 1, 10, 1, 10, 1]' is invalid for input of size 225

**Comment by zhaohm14** [comment]
I'm encountering the same issue as you. Has this problem been resolved?

**Comment by Wyzix33** [comment]
try using multiple of 320 for sizes
