### ISSUE TITLE
Train script hangs with no errors

### ISSUE THREAD

**Issue by abaybektursun** [clovaai/donut#115]
```bash 
root@spot-a100-1670595978:/app# python3 train.py --config config/train_cord.yaml --pretrained_model_name_or_path
 "naver-clova-ix/donut-base" --dataset_name_or_paths "['/app/jsonl']" --exp_version "abay_experiment"

resume_from_checkpoint_path: None
result_path: ./result
pretrained_model_name_or_path: naver-clova-ix/donut-base
dataset_name_or_paths: 
  - /app/jsonl
sort_json_key: False
train_batch_sizes:
  - 8
val_batch_sizes:
  - 1
input_size: 
  - 1280
  - 960
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022  
lr: 3e-05
warmup_steps: 300
num_training_samples_per_epoch: 800
max_epochs: 30
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True
exp_name: train_cord
exp_version: abay_experiment
Config is saved at result/train_cord/abay_experiment/config.yaml
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/utilities/seed.py:48: LightningDeprecationWarning: `pytorch_lightning.utilities.seed.seed_everything` has been deprecated in v1.8.0 and will be removed in v1.10.0. Please use `lightning_lite.utilities.seed.seed_everything` instead.
  rank_zero_deprecation(
Global seed set to 2022
/usr/local/lib/python3.8/dist-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Some weights of DonutModel were not initialized from the model checkpoint at naver-clova-ix/donut-base and are newly initialized because the shapes did not match:
- encoder.model.layers.0.blocks.1.attn_mask: found shape torch.Size([3072, 100, 100]) in the checkpoint and torch.Size([768, 100, 100]) in the model instantiated
- encoder.model.layers.1.blocks.1.attn_mask: found shape torch.Size([768, 100, 100]) in the checkpoint and torch.Size([192, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.1.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.3.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.5.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.7.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.9.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.11.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.2.blocks.13.attn_mask: found shape torch.Size([192, 100, 100]) in the checkpoint and torch.Size([48, 100, 100]) in the model instantiated
- encoder.model.layers.3.blocks.1.attn_mask: found shape torch.Size([48, 100, 100]) in the checkpoint and torch.Size([12, 100, 100]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Resolving data files: 100%|████████████████████████████████████████████████████████████| 16197/16197 [00:00<00:00, 27669.39it/s]
Resolving data files: 100%|██████████████████████████████████████████████████████████████| 2001/2001 [00:00<00:00, 13913.31it/s]
Resolving data files: 100%|██████████████████████████████████████████████████████████████| 1801/1801 [00:00<00:00, 14983.16it/s]
Using custom data configuration jsonl-9ae412abd68dd439
Found cached dataset imagefolder (/root/.cache/huggingface/datasets/imagefolder/jsonl-9ae412abd68dd439/0.0.0/37fbb85cc714a338bea574ac6c7d0b5be5aff46c1862c1989b20e0771199e93f)
```
Just hangs here, nothing happens

**Comment by abaybektursun** [comment]
This is what I see after interrupt:
```
^CTraceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 87, in train
    sort_json_key=config.sort_json_key,
  File "/app/donut/donut/util.py", line 86, in __init__
    for gt_json in gt_jsons  # load json from list of json
  File "/app/donut/donut/util.py", line 86, in <listcomp>
    for gt_json in gt_jsons  # load json from list of json
  File "/app/donut/donut/model.py", line 514, in json2token
    + fr"</s_{k}>"
  File "/app/donut/donut/model.py", line 519, in json2token
    [self.json2token(item, update_special_tokens_for_json_key, sort_json_key) for item in obj]
  File "/app/donut/donut/model.py", line 519, in <listcomp>
    [self.json2token(item, update_special_tokens_for_json_key, sort_json_key) for item in obj]
  File "/app/donut/donut/model.py", line 510, in json2token
    self.decoder.add_special_tokens([fr"<s_{k}>", fr"</s_{k}>"])
  File "/app/donut/donut/model.py", line 205, in add_special_tokens
    newly_added_num = self.tokenizer.add_special_tokens({"additional_special_tokens": sorted(set(list_of_tokens))})
  File "/root/anaconda3/envs/donut_official/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 928, in add_special_tokens
    added_tokens += self.add_tokens(value, special_tokens=True)
  File "/root/anaconda3/envs/donut_official/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 985, in add_tokens
    return self._add_tokens(new_tokens, special_tokens=special_tokens)
  File "/root/anaconda3/envs/donut_official/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 445, in _add_tokens
    self._create_trie(self.unique_no_split_tokens)
  File "/root/anaconda3/envs/donut_official/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 455, in _create_trie
    trie.add(token)
  File "/root/anaconda3/envs/donut_official/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 86, in add
    ref[char] = char in ref and ref[char] or {}
KeyboardInterrupt
```

**Comment by abaybektursun** [comment]
I tried to downgrade to 1.0.8 same issue @gwkrsrch

**Comment by abaybektursun** [comment]
Another interrupt: 
```
^CTraceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 87, in train
    sort_json_key=config.sort_json_key,
  File "/app/donut/donut/util.py", line 86, in __init__
    for gt_json in gt_jsons  # load json from list of json
  File "/app/donut/donut/util.py", line 86, in <listcomp>
    for gt_json in gt_jsons  # load json from list of json
  File "/app/donut/donut/model.py", line 516, in json2token
    + fr"</s_{k}>"
  File "/app/donut/donut/model.py", line 521, in json2token
    [self.json2token(item, update_special_tokens_for_json_key, sort_json_key) for item in obj]
  File "/app/donut/donut/model.py", line 521, in <listcomp>
    [self.json2token(item, update_special_tokens_for_json_key, sort_json_key) for item in obj]
  File "/app/donut/donut/model.py", line 512, in json2token
    self.decoder.add_special_tokens([fr"<s_{k}>", fr"</s_{k}>"])
  File "/app/donut/donut/model.py", line 207, in add_special_tokens
    self.model.resize_token_embeddings(len(self.tokenizer))
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1238, in resize_token_embeddings
    model_embeds = self._resize_token_embeddings(new_num_tokens)
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1253, in _resize_token_embeddings
    new_embeddings = self._get_resized_embeddings(old_embeddings, new_num_tokens)
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/modeling_utils.py", line 1307, in _get_resized_embeddings
    new_embeddings = nn.Embedding(new_num_tokens, old_embedding_dim)
  File "/app/donut/venv/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 142, in __init__
    self.reset_parameters()
  File "/app/donut/venv/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 151, in reset_parameters
    init.normal_(self.weight)
  File "/app/donut/venv/lib/python3.7/site-packages/torch/nn/init.py", line 155, in normal_
    return _no_grad_normal_(tensor, mean, std)
  File "/app/donut/venv/lib/python3.7/site-packages/torch/nn/init.py", line 19, in _no_grad_normal_
    return tensor.normal_(mean, std)
KeyboardInterrupt
```

**Comment by abaybektursun** [comment]
Looks like getting stuck recursively parsing the tokens?

**Comment by abaybektursun** [comment]
After running all night:
```
^CTraceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 87, in train
    sort_json_key=config.sort_json_key,
  File "/app/donut/donut/util.py", line 86, in __init__
    for gt_json in gt_jsons  # load json from list of json
  File "/app/donut/donut/util.py", line 86, in <listcomp>
    for gt_json in gt_jsons  # load json from list of json
  File "/app/donut/donut/model.py", line 516, in json2token
    + fr"</s_{k}>"
  File "/app/donut/donut/model.py", line 521, in json2token
    [self.json2token(item, update_special_tokens_for_json_key, sort_json_key) for item in obj]
  File "/app/donut/donut/model.py", line 521, in <listcomp>
    [self.json2token(item, update_special_tokens_for_json_key, sort_json_key) for item in obj]
  File "/app/donut/donut/model.py", line 512, in json2token
    self.decoder.add_special_tokens([fr"<s_{k}>", fr"</s_{k}>"])
  File "/app/donut/donut/model.py", line 205, in add_special_tokens
    newly_added_num = self.tokenizer.add_special_tokens({"additional_special_tokens": sorted(set(list_of_tokens))})
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 928, in add_special_tokens
    added_tokens += self.add_tokens(value, special_tokens=True)
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 985, in add_tokens
    return self._add_tokens(new_tokens, special_tokens=special_tokens)
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 445, in _add_tokens
    self._create_trie(self.unique_no_split_tokens)
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 455, in _create_trie
    trie.add(token)
  File "/app/donut/venv/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 86, in add
    ref[char] = char in ref and ref[char] or {}
KeyboardInterrupt
```
Yeah, looks like stop in infinite loop

**Comment by abaybektursun** [comment]
I think I figured it out: Every json key considered to be a special token. So it spends long time doing the `Trie.add` in slow python code (probably use HuggingFace's fast tokenizer?). In my case every key is unique so this approach will not work, I think documentation should reflect the limitations of the acceptable json structures. I will restructure my json dataset and try training again.

**Comment by abaybektursun** [comment]
Yep, after restructuring my json it's training. Tokenization still takes couple minutes though.

**Comment by Rakshith12-pixel** [comment]
Hey @abaybektursun . So are you saying that, we cannot keep many fields in the gt_parses json object? Please help as my training has also hung up.
