### ISSUE TITLE
Getting pyarrow error

### ISSUE THREAD

**Issue by ankitgoyalIQ** [clovaai/donut#146]
Great work, I am following your paper and attempting classification task on custom dataset. I have dataset in following format:

{"file_name": "1/2png", "ground_truth": "{\"gt_parse\": {\"class\": \"1\"}}"}{"file_name": "1/5d53.png", "ground_truth": "{\"gt_parse\": {\"class\": \"1\"}}"}
{"file_name": "1/436-1.png", "ground_truth": "{\"gt_parse\": {\"class\": \"1\"}}"}{"file_name": "1/3541.png", "ground_truth": "{\"gt_parse\": {\"class\": \"1\"}}"}
{"file_name": "1/472-1.png", "ground_truth": "{\"gt_parse\": {\"class\": \"1\"}}"}{"file_name": "1/237-1.png", "ground_truth": "{\"gt_parse\": {\"class\": \"1\"}}"}

I am getting following error when I try to invoke training. Will highly appreciate any guidance you can provide. 

Traceback (most recent call last):
  File "./donut/train.py", line 149, in <module>
    train(config)
  File "./donut/train.py", line 78, in train
    DonutDataset(
  File "/home/ec2-user/Donut/donut/donut/util.py", line 63, in __init__
    self.dataset = load_dataset(dataset_name_or_path, split=self.split)
  File "/home/ec2-user/anaconda3/envs/donut_official_1/lib/python3.8/site-packages/datasets/load.py", line 1758, in load_dataset
    builder_instance.download_and_prepare(
  File "/home/ec2-user/anaconda3/envs/donut_official_1/lib/python3.8/site-packages/datasets/builder.py", line 860, in download_and_prepare
    self._download_and_prepare(
  File "/home/ec2-user/anaconda3/envs/donut_official_1/lib/python3.8/site-packages/datasets/builder.py", line 1612, in _download_and_prepare
    super()._download_and_prepare(
  File "/home/ec2-user/anaconda3/envs/donut_official_1/lib/python3.8/site-packages/datasets/builder.py", line 931, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
  File "/home/ec2-user/anaconda3/envs/donut_official_1/lib/python3.8/site-packages/datasets/packaged_modules/folder_based_builder/folder_based_builder.py", line 189, in _split_generators
    pa_metadata_table = self._read_metadata(downloaded_metadata_file)
  File "/home/ec2-user/anaconda3/envs/donut_official_1/lib/python3.8/site-packages/datasets/packaged_modules/folder_based_builder/folder_based_builder.py", line 260, in _read_metadata
    return paj.read_json(f)
  File "pyarrow/_json.pyx", line 259, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: straddling object straddles two block boundaries (try to increase block size?)

**Comment by balajiChundi** [comment]
return paj.read_json(f)
  File "pyarrow/_json.pyx", line 258, in pyarrow._json.read_json
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: JSON parse error: Column() changed from object to string in row 0

I am also getting a similar error? @ankitgoyalIQ were you able to solve this error?
