### ISSUE TITLE
Couldn't connect to 'https://huggingface.co'

### ISSUE THREAD

**Issue by mmhzlrj** [clovaai/donut#252]
'```
(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /naver-clova-ix/donut-base-finetuned-docvqa/resolve/official/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001C56090FB48>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 873240bb-b19d-4343-aef9-ef44c68c3677)')' thrown while requesting HEAD https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa/resolve/official/config.json
Traceback (most recent call last):
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\transformers\utils\hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\huggingface_hub\file_download.py", line 1292, in hf_hub_download
    "Connection error, and we cannot find the requested files in"
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/JupyterProject/donut/app.py", line 49, in <module>
    pretrained_model = DonutModel.from_pretrained(args.pretrained_path)
  File "D:\JupyterProject\donut\donut\model.py", line 597, in from_pretrained
    model = super(DonutModel, cls).from_pretrained(pretrained_model_name_or_path, revision="official", *model_args, **kwargs)
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\transformers\modeling_utils.py", line 2025, in from_pretrained
    **kwargs,
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\transformers\configuration_utils.py", line 532, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\transformers\configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\transformers\configuration_utils.py", line 626, in _get_config_dict
    _commit_hash=commit_hash,
  File "C:\Users\Admin\miniconda3\envs\donut_official\lib\site-packages\transformers\utils\hub.py", line 444, in cached_file
    f"We couldn't connect to '{HUGGINGFACE_CO_RESOLVE_ENDPOINT}' to load this file, couldn't find it in the"
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like naver-clova-ix/donut-base-finetuned-docvqa is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
```
```

For some reasons, my internet cannot connect to huggingface directly. But I can download files from website and put them in folder locally. Please tell me where should I go to download what files to place them where. Thank you

**Comment by FNsi** [comment]
`Please tell me where should I go to download what files to place them where. `

China nearby 😆
