### ISSUE TITLE
ValueError: Unknown split "validation". Should be one of ['train'].

### ISSUE THREAD

**Issue by Near-Start** [clovaai/donut#57]
I only run: 
python train.py --config config/train_cord.yaml --pretrained_model_name_or_path "naver-clova-ix/donut-base" --dataset_name_or_paths '["naver-clova-ix/cord-v2"]' --exp_version "test_experiment"
It has such an error, why? Thanks for your help!

Traceback (most recent call last):
  File "train.py", line 150, in <module>
    train(config)
  File "train.py", line 87, in train
    sort_json_key=config.sort_json_key,
  File "/home/donut/donut/util.py", line 64, in __init__
    self.dataset = load_dataset(dataset_name_or_path, split=self.split)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/load.py", line 1644, in load_dataset
    ds = builder_instance.as_dataset(split=split, ignore_verifications=ignore_verifications, in_memory=keep_in_memory)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/builder.py", line 793, in as_dataset
    disable_tqdm=False,
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/utils/py_utils.py", line 206, in map_nested
    return function(data_struct)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/builder.py", line 817, in _build_single_dataset
    in_memory=in_memory,
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/builder.py", line 889, in _as_dataset
    in_memory=in_memory,
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/arrow_reader.py", line 213, in read
    files = self.get_file_instructions(name, instructions, split_infos)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/arrow_reader.py", line 187, in get_file_instructions
    name, split_infos, instruction, filetype_suffix=self._filetype_suffix
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/arrow_reader.py", line 110, in make_file_instructions
    absolute_instructions = instruction.to_absolute(name2len)
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/arrow_reader.py", line 618, in to_absolute
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/arrow_reader.py", line 618, in <listcomp>
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/home/anaconda3/envs/pytorch/lib/python3.6/site-packages/datasets/arrow_reader.py", line 433, in _rel_to_abs_instr
    raise ValueError('Unknown split "{}". Should be one of {}.'.format(split, list(name2len)))
ValueError: Unknown split "validation". Should be one of ['train'].

**Comment by SamSamhuns** [comment]
This is an issue with the `huggingface` `datasets` library. If you have files inside your validation dir that start with `train`, they will not be recognized as validation.
Check https://github.com/huggingface/datasets/issues/4895

**Comment by Near-Start** [comment]
> This is an issue with the `huggingface` `datasets` library. If you have files inside your validation dir that start with `train`, they will not be recognized as validation. Check [huggingface/datasets#4895](https://github.com/huggingface/datasets/issues/4895)

Thanks for your reply! I understand.

**Comment by ritwikmishra** [comment]
I was getting this same error while loading a dataset in Huggingface dataset format from a json object. I dig through the library of the huggingface library to find the root cause of this problem.

I found out ```env_name/lib/python3.9/site-packages/datasets/data_files.py``` has a function called ```sanitize_patterns``` which uses ```str(Split.TRAIN)``` as the ```SANITIZED_DEFAULT_SPLIT```. That is the reason why every split is being treated as "train" only. I changed the function to as follows:

```
def sanitize_patterns(patterns: Union[Dict, List, str]) -> Dict[str, Union[List[str], "DataFilesList"]]:
    """
    Take ...
    """
    current_split = SANITIZED_DEFAULT_SPLIT
    if 'test' in str(patterns).split('/')[-1] or 'eval' in str(patterns).split('/')[-1]: # if the file name contains test or eval
        current_split = str(Split.TEST)
    elif 'val' in str(patterns).split('/')[-1] or 'dev' in str(patterns).split('/')[-1]: # if the file name contains val or dev
        current_split = str(Split.VALIDATION)

    if isinstance(patterns, dict):
        return {str(key): value if isinstance(value, list) else [value] for key, value in patterns.items()}
    elif isinstance(patterns, str):
        return {current_split: [patterns]}
    elif isinstance(patterns, list):
        return {current_split: patterns}
    else:
        return {current_split: list(patterns)}
```

This solved the issue for me.
