### ISSUE TITLE
Image at {file_relpath} doesn't have metadata in {downloaded_metadata_file}

### ISSUE THREAD

**Issue by Meghna199** [clovaai/donut#69]
I'm trying to retrain donut model on my custom dataset, and made the dataset using script. I put metadata.jsonl file for all the images along with images in train folder. Here I'm providing starting 4 lines of my metadata.jsonl file:
metadata 
{"file_name": "img1.jpeg", "ground_truth": "{\"gt_parse\": {\"patient name\": \"XYZ\"}}"} {"file_name": "img10.jpeg", "ground_truth": "{\"gt_parse\": {\"patient name\": \"ABC\"}}"} {"file_name": "img11.jpeg", "ground_truth": "{\"gt_parse\": {\"patient name\": \"XYZ\"}}"} {"file_name": "img12.jpeg", "ground_truth": "{\"gt_parse\": {\"patient name\": \"ABC\"}}"} {"file_name": "img13.jpeg", "ground_truth": "{\"gt_parse\": {\"patient name\": \"XYZ\"}}"}

After running the following command for traing the model:
python train.py --config D:/donut_project/donut/config/pname_train.yaml

And in the console I'm getting following error
Extracting data files: 0it [00:00, ?it/s] | 0/3 [00:00<?, ?obj/s] Traceback (most recent call last): File "train.py", line 149, in <module> | 0/3 [00:00<?, ?obj/s] train(config) File "train.py", line 87, in train | 0/3 [00:00<?, ?obj/s] sort_json_key=config.sort_json_key, File "D:\donut_project\donut\donut\util.py", line 64, in __init__ | 0/3 [00:00<?, ?obj/s] self.dataset = load_dataset(dataset_name_or_path, split=self.split) | 0/3 [00:00<?, ?obj/s] File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\datasets\load.py", line 1751, in load_dataset use_auth_token=use_auth_token, File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\datasets\builder.py", line 705, in download_and_prepare | 0/3 [00:00<?, ?obj/s] dl_manager=dl_manager, verify_infos=verify_infos, **download_and_prepare_kwargs File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\datasets\builder.py", line 1227, in _download_and_prepare super()._download_and_prepare(dl_manager, verify_infos, check_duplicate_keys=verify_infos) File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\datasets\builder.py", line 793, in _download_and_prepare self._prepare_split(split_generator, **prepare_split_kwargs) File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\datasets\builder.py", line 1216, in _prepare_split desc=f"Generating {split_info.name} split", File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\tqdm\std.py", line 1195, in __iter__ for obj in iterable: File "C:\ProgramData\Anaconda3\envs\donut_official\lib\site-packages\datasets\packaged_modules\imagefolder\imagefolder.py", line 286, in _generate_examples f"Image at {file_relpath} doesn't have metadata in {downloaded_metadata_file}." ValueError: Image at img1.jpeg doesn't have metadata in D:\donut_project\database\train\metadata.jsonl.

I tried multiple things but can't get the solution to deal with this error.
Please someone help me out for this problem ASAP.

**Comment by vishal-nayak1** [comment]
@Meghna199 Hey, it seems like the image '**img1.jpeg**' does not have meta data in jsonl file.Either you need to add it or remove the image from the dataset folder.
**dataset** folder structure should be like this-
**dataset**-
       -**metadata.jsonl**
       -**img1.jpeg**
       -**img2.jpeg**
       -**img3.jpeg**.....so on.
where metadata.jsonl file have data like this-
{"file_name": {'./img1.jpeg'}, "ground_truth": "{\"gt_parse\": {ground_truth_parse}, ... {other_metadata_not_used} ... }"}
{"file_name": {'./img2.jpeg'}, "ground_truth": "{\"gt_parse\": {ground_truth_parse}, ... {other_metadata_not_used} ... }"}......so on

Note: make sure **dataset** folder should have only images whose metadata are present in metadata.jsonl file.And No other images(No metadata available) should be present in the dataset directory.

**Comment by Meghna199** [comment]
Data in metadata.jsonl file is same as you mentioned. You can check as I provided copy of the same. And structure of dataset folder is also same, but stil facing same error.

**Comment by vishal-nayak1** [comment]
Firstly, Try to use following code to write on metadata.jsonl file-

**import json
with  open("./metadata.jsonl", 'w') as f:
    dict1 = {'file_name': image_path,  'ground_truth': json.dumps({'gt_parse': dict(original_text)})}
    f.write(json.dumps(dict1) + "\n")**

Output of metadata.jsonl file should look like this-
{"file_name": "img1.jpg", "ground_truth": "{\"gt_parse\": {\"NAME\": \"ARUN\", \"TITLE\": \"Mr.\"}}"}
{"file_name": "img2.jpg", "ground_truth": "{\"gt_parse\": {\"NAME\": \"mukesh kumar\", \"TITLE\": \"Mr.\"}}"}

Secondly, you can check-
Note: make sure dataset folder should have only images whose metadata are present in metadata.jsonl file.And No other images(No metadata available) should be present in the dataset directory.

**Comment by Meghna199** [comment]
Doing the same thing, and even checking for single image also but still facing the same error that image doesn't have metadata.jsonl.
And while trying different approach I'm facing a different error which is
ValueError: Image must of type`PIL.Image.Image', 'np.ndarray' or 'torch.Tensor'(single example), 'List[PIL.Image.Image]', 'List[no.ndarray]' or 'List[torch.Tensor]' (batch of examples).
