### ISSUE TITLE
.jsonl file format for training

### ISSUE THREAD

**Issue by MartinHaus1993** [clovaai/donut#76]
Hi,
Thanks for this great project!!

I have been trying to create .jsonl files for training and validation and run into some issues here. I have checked with a json validator that the lines as such are in a valid json format, and they are. My file looks like this:

`{"file_name": "./abc.png", "ground_truth": "{\"gt_parse\": [{\"order_date\": \"11th May, 2010\", {\"Transfers\":[{\"product\":\"one\",\"transfer_date\":null}]}}]}"}`

which looks like this if reformatted for making it easier readable here:

```
{
	"file_name": "./abc.png",
	"ground_truth": "{\"gt_parse\": [{\"order_date\": \"11th May, 2010\", {\"Transfers\":[{\"product\":\"one\",\"transfer_date\":null}]}}]}"
}
```
Do I understand correctly that ground_truth contains a simple string which hence requires to escape all following _"s_ within the string?

Running this results in a json related error:
```
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 78, in train
    DonutDataset(
  File "util.py", line 69, in __init__
    ground_truth = json.loads(sample["ground_truth"])
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 47 (char 46)
```

Character 46 refers to to the first **"** of "ground_truth".

I might be missing something obvious here, so any hints would be very helpful.

Thanks!

Best,
Martin

**Comment by MartinHaus1993** [comment]
(Solved by generating the .jsonl file with the help of json.dumps())
