### ISSUE TITLE
RuntimeError: unmatched '}' in format string

### ISSUE THREAD

**Issue by s711183122** [clovaai/donut#89]
My dataset is like:
`
{"file_name": "00.jpg", "ground_truth": "{\"gt_parse\": {\"number\": \"PT-26931468\", \"date\": \"2021-07-23 00:00:00\", \"seller\": \"28710621.0\", \"total\": \"225.0\"}}"}
{"file_name": "04.jpg", "ground_truth": "{\"gt_parse\": {\"number\": \"EQ-32999192\", \"date\": \"2018-08-23 00:00:00\", \"seller\": \"83963229.0\", \"total\": \"8185.0\"}}"}
`
but when i train it,
it will show 'RuntimeError: unmatched '}' in format string'

**Comment by s711183122** [comment]
Traceback (most recent call last):
  File "train.py", line 148, in <module>
    train(config)
  File "train.py", line 132, in train
    trainer.fit(model_module, data_module)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 580, in fit
    self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\trainer\call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\strategies\launchers\subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 621, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 994, in _run
    self.strategy.setup_environment()
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 153, in setup_environment
    self.setup_distributed()
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\pytorch_lightning\strategies\ddp.py", line 204, in setup_distributed
    _init_dist_connection(self.cluster_environment, self._process_group_backend, timeout=self._timeout)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\lightning_lite\utilities\distributed.py", line 237, in _init_dist_connection
    torch.distributed.init_process_group(torch_distributed_backend, rank=global_rank, world_size=world_size, **kwargs)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\torch\distributed\distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\torch\distributed\rendezvous.py", line 244, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "C:\Users\pc.admin\.conda\envs\donut\lib\site-packages\torch\distributed\rendezvous.py", line 177, in _create_c10d_store
    return TCPStore(hostname, port, world_size, start_daemon, timeout, multi_tenant=True)
RuntimeError: unmatched '}' in format string
